name: "Test"
on:
  push:
jobs:
  native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-env -i skopeo -f '<nixpkgs>'
    - run: skopeo login -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}" ghcr.io
    - run: nix --extra-experimental-features "nix-command flakes" run .#SIGH.lock
    - run: nix --extra-experimental-features "nix-command flakes" build .#SIGH --print-build-logs

  container:
    runs-on: ubuntu-latest
    container: nixos/nix
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - run: nix-env -i skopeo -f '<nixpkgs>'
    - run: skopeo login -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}" ghcr.io
    - run: chown -R $USER $HOME $PWD
    - run: nix --extra-experimental-features "nix-command flakes" run .#SIGH.lock
    - run: nix --extra-experimental-features "nix-command flakes" build .#SIGH --print-build-logs
